// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH0zpmTi79e_eDHvPD66hZjjccsC2ZoYg',
    appId: '1:694380235270:web:6b05f6136d7378b296d187',
    messagingSenderId: '694380235270',
    projectId: 'tools-tracker-globe',
    authDomain: 'tools-tracker-globe.firebaseapp.com',
    storageBucket: 'tools-tracker-globe.firebasestorage.app',
    measurementId: 'G-CPE0KGE0YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZamhTYd2ccLnugcg2f0cY1JABIyzjDSA',
    appId: '1:694380235270:android:88825a7acd33c3c696d187',
    messagingSenderId: '694380235270',
    projectId: 'tools-tracker-globe',
    storageBucket: 'tools-tracker-globe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1VhXqe_wRpka828n45V-mp8gJnsuM6M',
    appId: '1:694380235270:ios:148b44be3f05384696d187',
    messagingSenderId: '694380235270',
    projectId: 'tools-tracker-globe',
    storageBucket: 'tools-tracker-globe.firebasestorage.app',
    iosBundleId: 'com.example.toolsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg1VhXqe_wRpka828n45V-mp8gJnsuM6M',
    appId: '1:694380235270:ios:148b44be3f05384696d187',
    messagingSenderId: '694380235270',
    projectId: 'tools-tracker-globe',
    storageBucket: 'tools-tracker-globe.firebasestorage.app',
    iosBundleId: 'com.example.toolsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH0zpmTi79e_eDHvPD66hZjjccsC2ZoYg',
    appId: '1:694380235270:web:9ed5040827f5c9bf96d187',
    messagingSenderId: '694380235270',
    projectId: 'tools-tracker-globe',
    authDomain: 'tools-tracker-globe.firebaseapp.com',
    storageBucket: 'tools-tracker-globe.firebasestorage.app',
    measurementId: 'G-LSVH0N58L3',
  );

}